### ISSUE TITLE
Step 4 of deploy does not work if using a credential profile

### ISSUE THREAD

**Issue by scmc** [UBC-CIC/commit2act#26]
If the user is using a credential profile aws s3api commands need to me modified 

https://github.com/UBC-CIC/commit2act/blob/main/backend/scripts/lambda_trigger.sh

**Comment by stefansson30952** [comment]
Instead of using a bash script to create make the changes to the s3 bucket and lambda a cdk stack was created for step 4. Users can now use a credential profile.
