### ISSUE TITLE
Step 3 of deployment does not work

### ISSUE THREAD

**Issue by stefansson30952** [UBC-CIC/commit2act#27]

**Comment by stefansson30952** [comment]
I got an error with cloudFront:

CREATE_FAILED  AWS::CloudFront::Distribution CloudFrontDistribution  Resource handler returned message:

"Exceeded attempts to wait" (RequestToken: f8cd30fa-51ea-dd3b-88d5-3e554074ed01, HandlerErrorCode: NotStabilized)

**Comment by christyylam** [comment]
Getting error with cloudformation "The following resource(s) failed to create: [isQUizANswerCorrectResolver, getAllGroupsForUserResolver...] (all the resolvers)". 

This error happened after I deleted the amplify app and the cloudformation stack in us-east-1 and tried to do a fresh deploy

**Comment by stefansson30952** [comment]
Error was dynamic references to parameter store have a limit of 40 per template. The template was referencing more than 40.
