### ISSUE TITLE
Error loading pages when signing in with the cloudformation template cognito admin user account

### ISSUE THREAD

**Issue by christyylam** [UBC-CIC/commit2act#28]
Error with the cognito admin user account created by the cloudformation template. It makes the account properly but when I use that account to login for the first time, the query that gets the user has a mapping template error
![image](https://user-images.githubusercontent.com/77952422/190276576-f29b5e52-c5c5-4769-8ef7-e5517b367a98.png)

**Comment by stefansson30952** [comment]
Issue fixed. The admin user had the wrong settings in the cloud formation template.
